final List<Map<String, dynamic>> dumyData = [
  {
    "id": 1,
    "name": "Shangrila Ketchup",
    "qty": 34.0,
    "category": "Food",
    "price": 210.0,
    "brand": "Shangrila",
  },
  {
    "id": 2,
    "name": "Kurkure Chatpata Masoor Mix ",
    "qty": 12.0,
    "category": "Snack",
    "price": 30.0,
    "brand": "PepsiCo",
  },
  {
    "id": 3,
    "name": "SUNSILK Shampo Long & Healthy",
    "qty": 11.0,
    "category": "Shampo",
    "price": 180.0,
    "brand": "Unilever",
  },
  {
    "id": 4,
    "name": "LIFEBUOY SOAP",
    "qty": 34.0,
    "category": "Soap",
    "price": 70.0,
    "brand": "Unilever",
  },
  {
    "id": 5,
    "name": "Hemani Onion Oil",
    "qty": 65.0,
    "category": "Hair Oil",
    "price": 510.0,
    "brand": "Hemani",
  },
  {
    "id": 6,
    "name": "Mon Salwa Cheese Samosa",
    "qty": 91.0,
    "category": "Snack",
    "price": 970.0,
    "brand": "Mon Salwa",
  },
  {
    "id": 7,
    "name": "Blue Band 100g",
    "qty": 31.0,
    "category": "Food",
    "price": 250.0,
    "brand": "Unilever",

  },
  {
    "id": 8,
    "name": "Mars Ice Cream",
    "qty": 35.0,
    "category": "Food",
    "price": 100.0,
    "brand": "The Mars family"
  },
  {
    "id": 9,
    "name": "LEMON MAX BAR",
    "qty": 48.0,
    "category": "Dishwasher",
    "price": 120.0,
    "brand": "Maxbar",
  },
  {
    "id": 10,
    "name": "Shan beef biryani masala 60gm",
    "qty": 78.0,
    "category": "Masala",
    "price": 90.0,
    "brand": "Shan",
  },
  {
    "id": 11,
    "name": "shan bihari kabab masala 50gm",
    "qty": 89.0,
    "category": "Masala",
    "price": 80.0,
    "brand": "Shan",
  },
];
